### ISSUE TITLE
Servidor RPC No Disponible

### ISSUE THREAD

**Issue by asanderjs** [AndresRamos/Contpaqi.Sdk.Contabilidad#1]
Buenas Tardes,
Al intentar iniciar Conexion en el Programa de ejemplo aparece un error sobre el Servidor RPC
No tiene alguna idea o solucion que pueda usar? por mas que busco no encuentro nada que ayude.
![error](https://user-images.githubusercontent.com/108588093/200137774-49e60f70-204c-4782-863d-8ae0a16434e0.png)

Gracias de Antemano

**Comment by AndresRamos** [comment]
Tienes instalado el sistema de CONTPAQi Contabilidad en esa maquina?

**Comment by asanderjs** [comment]
Ah, si, ya lo pude resolver, era un problema con la licencia de CONTPAQi Contabilidad

Gracias por la atencion.
